### ISSUE TITLE
TTransportException: TTransportException(type=4, message='TSocket read 0 bytes')

### ISSUE THREAD

**Issue by mohamedniyaz1996** [python-happybase/aiohappybase#2]
I tried to use this library with HBase version 0.98.6-cdh5.3.0 it works well,
But when I tried to use at version 2.1.0-cdh6.2.1 , I got below error :

```
TTransportException: TTransportException(type=4, message='TSocket read 0 bytes')
```

**Comment by aiudirog** [comment]
I rebuilt the testing container with 2.1.0 and wasn't able to reproduce this error with the standard test suite. Could provide me with some code that can cause the error? 

Also, just to check, are you sure the server is configured for Thrift over a binary socket and not HTTP? IIRC, I've gotten this error trying to connect to an HTTP HBase Thrift server before. Look for "hbase.regionserver.thrift.http" in hbase-site.xml or other config relevant files.

If you do end up needing HTTP support, I've been working on it using HTTPX over at https://github.com/aiudirog/ThriftPy2-HTTPX-Client, but it's in limbo until HTTPX v1.0 because the API is unstable.

**Comment by aiudirog** [comment]
@mohamedniyaz1996 Are you still experiencing this error?

**Comment by mohamedniyaz1996** [comment]
Hi @aiudirog , sorry for delayed response - as you said this is not a bug with aiohappybase - this is because Thrift is not configured over binary socket.

Now it works fine with 2.1.0.

**Comment by aiudirog** [comment]
Awesome, I'm glad you solved your problem. I'll be adding built-in support soon for the the thriftpy2-httpx-client I just released, so if you want to use HTTP, it should be pretty easy soon.

**Comment by mohamedniyaz1996** [comment]
Thanks @aiudirog - Awaiting for this !

**Comment by aiudirog** [comment]
It's actually all out! Upgrade aiohappybase and install the http extra: `pip install -U aiohappybase[http]`. Once it is installed, you can pass `client='http'` to `Connection` to use it. Any extra kwargs will be passed through to initialize the HTTPX `Client`.
